In [46]:
import numpy as np


def generate_copy_sequence(length, bits=8):
    seq = np.zeros([length, bits+1], dtype=np.float32)
    for idx in range(length):
        seq[idx, :bits] = np.random.rand(bits).round()
    flag_delim = np.zeros((1,bits+1))

    flag_delim[0,-1]=1
    seq = np.concatenate((seq,flag_delim),axis=0)
    return seq

In [48]:
print(generate_copy_sequence(30))

(1, 9)
(30, 9)
[[0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 1. Filling in the Gaps

### a) Constraints of Parameters

### b) Diagram of Dependencies